name: Sync Public to Private

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v2
        with:
          repository: Anandaraj-SF4202/demo
          ref: main

      - name: Configure Git
        run: |
          git config --global user.email "anandaraj.sf4202@gmail.com"
          git config --global user.name "Anandaraj-SF4202"
      
      - name: Push Changes to Private Repository
        run: |
          git remote add private_repo https://username:token@github.com/Anandaraj-SF4202/demo1.git
          git checkout -b sync-branch
          git push private_repo sync-branch:main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PRIVATE_REPO_PAT }}
          repository: Anandaraj-SF4202/demo1
          branch: sync-branch
          title: 'Merge changes from public repository'
          body: 'Automatically generated pull request from public repository to private repository.'
          labels: 'automated'
          base: main
